export type Book = {
  id: string;
  title: string;
  author: string;
  isbn: string;
  category: string;
  price: number;
  description: string;
  cover_image: string;
  rating: number;
  stock: number;
  published_year: number;
};

export const books: Book[] = [
  {
    id: "1",
    title: "The Garden of Paper Birds",
    author: "Elena Marsh",
    isbn: "9780143127741",
    category: "Fiction",
    price: 14.99,
    description:
      "A sweeping family saga about three sisters who inherit a crumbling bookshop and the letters hidden inside its walls.",
    cover_image: "/covers/fiction.jpg",
    rating: 4.5,
    stock: 23,
    published_year: 2019,
  },
  {
    id: "2",
    title: "Where the River Remembers",
    author: "David Okafor",
    isbn: "9780062315007",
    category: "Fiction",
    price: 12.5,
    description:
      "Two childhood friends reunite after twenty years in their flood-prone hometown, confronting the secret that drove them apart.",
    cover_image: "/covers/fiction.jpg",
    rating: 4.2,
    stock: 31,
    published_year: 2021,
  },
  {
    id: "3",
    title: "The Last Lighthouse Keeper",
    author: "Ingrid Halvorsen",
    isbn: "9780735219092",
    category: "Fiction",
    price: 16.99,
    description:
      "On a remote Norwegian island, the final keeper of a decommissioned lighthouse keeps a vigil for the ship that never returned.",
    cover_image: "/covers/fiction.jpg",
    rating: 4.7,
    stock: 12,
    published_year: 2018,
  },
  {
    id: "4",
    title: "A Winter in Lisbon",
    author: "Rui Tavares",
    isbn: "9780525656296",
    category: "Fiction",
    price: 11.25,
    description:
      "A retired chef opens a tiny cafe in Alfama and finds his quiet life upended by the strangers who become regulars.",
    cover_image: "/covers/fiction.jpg",
    rating: 4.0,
    stock: 40,
    published_year: 2022,
  },
  {
    id: "5",
    title: "Echoes of Andromeda",
    author: "Kira Vasquez",
    isbn: "9780593135204",
    category: "Sci-Fi",
    price: 18.99,
    description:
      "A xenolinguist decodes a signal from a dead civilization, only to learn the message is a warning addressed to her by name.",
    cover_image: "/covers/scifi.jpg",
    rating: 4.6,
    stock: 18,
    published_year: 2023,
  },
  {
    id: "6",
    title: "The Titanium Dawn",
    author: "Marcus Chen",
    isbn: "9781250266773",
    category: "Sci-Fi",
    price: 15.75,
    description:
      "Humanity's first generation ship wakes its crew four centuries early, orbiting a planet that should not exist.",
    cover_image: "/covers/scifi.jpg",
    rating: 4.3,
    stock: 27,
    published_year: 2020,
  },
  {
    id: "7",
    title: "Clockwork Colony",
    author: "Amara Nwosu",
    isbn: "9780316411987",
    category: "Sci-Fi",
    price: 13.99,
    description:
      "On a terraformed Mars run by ancient automation, a young mechanic discovers the machines are planning something of their own.",
    cover_image: "/covers/scifi.jpg",
    rating: 4.1,
    stock: 0,
    published_year: 2021,
  },
  {
    id: "8",
    title: "The Glass Alibi",
    author: "Patricia Vance",
    isbn: "9780525539994",
    category: "Mystery",
    price: 13.5,
    description:
      "A defense attorney realizes her star witness in a murder trial is lying — to protect her own client.",
    cover_image: "/covers/mystery.jpg",
    rating: 4.4,
    stock: 35,
    published_year: 2022,
  },
  {
    id: "9",
    title: "Death at the Night Market",
    author: "Hiro Tanaka",
    isbn: "9780062857485",
    category: "Mystery",
    price: 12.99,
    description:
      "Inspector Sato navigates Osaka's lantern-lit markets to solve the poisoning of a beloved street-food vendor.",
    cover_image: "/covers/mystery.jpg",
    rating: 4.5,
    stock: 21,
    published_year: 2020,
  },
  {
    id: "10",
    title: "The Cartographer's Cipher",
    author: "Lucia Moretti",
    isbn: "9781250317155",
    category: "Mystery",
    price: 14.25,
    description:
      "A rare-maps dealer finds coded coordinates in a 17th-century atlas — and someone is willing to kill to keep them buried.",
    cover_image: "/covers/mystery.jpg",
    rating: 4.2,
    stock: 16,
    published_year: 2023,
  },
  {
    id: "11",
    title: "The Midnight Confession",
    author: "Samuel Reyes",
    isbn: "9780593318612",
    category: "Mystery",
    price: 11.99,
    description:
      "A late-night radio host receives a live on-air confession to an unsolved crime that happened in her own building.",
    cover_image: "/covers/mystery.jpg",
    rating: 3.9,
    stock: 29,
    published_year: 2021,
  },
  {
    id: "12",
    title: "Empires of the Silk Road",
    author: "Dr. Yasmin Farouk",
    isbn: "9780691234567",
    category: "History",
    price: 24.99,
    description:
      "A vivid retelling of two thousand years of trade, conquest, and ideas flowing between China and the Mediterranean.",
    cover_image: "/covers/history.jpg",
    rating: 4.8,
    stock: 14,
    published_year: 2019,
  },
  {
    id: "13",
    title: "The Forgotten Armada",
    author: "Cormac Byrne",
    isbn: "9780143133414",
    category: "History",
    price: 19.5,
    description:
      "The untold story of the sailors, spies, and storms that decided the fate of the Spanish Armada.",
    cover_image: "/covers/history.jpg",
    rating: 4.3,
    stock: 22,
    published_year: 2017,
  },
  {
    id: "14",
    title: "Revolution in the Air",
    author: "Nadia Petrova",
    isbn: "9780307389103",
    category: "History",
    price: 17.25,
    description:
      "How radio broadcasts carried the hopes and upheavals of the twentieth century into ordinary homes.",
    cover_image: "/covers/history.jpg",
    rating: 4.1,
    stock: 9,
    published_year: 2020,
  },
  {
    id: "15",
    title: "Code and Craft",
    author: "Anika Sharma",
    isbn: "9780134494166",
    category: "Tech",
    price: 29.99,
    description:
      "A practical philosophy of software design that treats programming as a craft — with principles that outlast any framework.",
    cover_image: "/covers/tech.jpg",
    rating: 4.6,
    stock: 33,
    published_year: 2021,
  },
  {
    id: "16",
    title: "The Algorithmic Mind",
    author: "Dr. Felix Andersson",
    isbn: "9780262046305",
    category: "Tech",
    price: 27.5,
    description:
      "An accessible tour of how machine learning systems actually learn, fail, and surprise their creators.",
    cover_image: "/covers/tech.jpg",
    rating: 4.4,
    stock: 26,
    published_year: 2022,
  },
  {
    id: "17",
    title: "Ship It Right",
    author: "Grace Liu",
    isbn: "9781492051354",
    category: "Tech",
    price: 21.99,
    description:
      "A field guide to calm, reliable software delivery — testing, rollouts, and on-call without the burnout.",
    cover_image: "/covers/tech.jpg",
    rating: 4.7,
    stock: 41,
    published_year: 2023,
  },
  {
    id: "18",
    title: "Bramble the Brave",
    author: "Molly Finch",
    isbn: "9781338214567",
    category: "Children",
    price: 8.99,
    description:
      "Bramble the fox is afraid of the dark — until a lost firefly needs his help finding the way home.",
    cover_image: "/covers/children.jpg",
    rating: 4.9,
    stock: 55,
    published_year: 2020,
  },
  {
    id: "19",
    title: "The Balloon That Loved Tuesdays",
    author: "Omar Delgado",
    isbn: "9780593118894",
    category: "Children",
    price: 7.5,
    description:
      "Every Tuesday a striped balloon floats over the village, and one curious girl decides to find out where it goes.",
    cover_image: "/covers/children.jpg",
    rating: 4.7,
    stock: 48,
    published_year: 2021,
  },
  {
    id: "20",
    title: "Grandpa's Star Map",
    author: "Aiko Yamada",
    isbn: "9781524765312",
    category: "Children",
    price: 9.25,
    description:
      "A grandfather and granddaughter trace constellations from their rooftop, weaving family stories into the stars.",
    cover_image: "/covers/children.jpg",
    rating: 4.8,
    stock: 0,
    published_year: 2022,
  },
];
